import PhoneCall from "./phone.png"
import Email from "./email.png"
import RussianFlag from "./russianflag.svg"
import UzbekFlag from "./uzbekflag.svg"
import UsaFlag from "./usaflag.svg"
import BigMeal from "./bigImg.png"
import Leaf from "./leaf.png"
import LeafMid from "./leaf-mid.png"
import LeafBL from "./leaf-bl.png"
import LeafRight from "./leaf-r.png"
import Meal1 from "./meal1.png"
import Ins from "./ins.png"
import BigPizza from "./bigpizza.png"
import NewDish from "./newMeal.png"
import NewPlace from "./newPlace.png"
import NewDrinks from "./newDrinks.png"
import ProfileImg from "./profileimg.png"
import ContactWithCall from './callContact.png'
import MapContact from './mapContact.png'
import SocialMediaContact from './socialmedia.png'
import MaskImg from './mask.png'
import OurMeals from './ourMeals.png'
import OurWays from './ourWays.png'
import HumoCart from './humoCart.svg'
import Uzcard from './uzcardCart.svg'
import VisaCart from './vizaCart.svg'
import MasterCart from './masterCart.svg'
import ApplePay from './applepayCart.svg'

export { ApplePay, MasterCart, VisaCart, Uzcard, HumoCart, OurWays, OurMeals, MaskImg, SocialMediaContact, MapContact, ContactWithCall, ProfileImg, NewDrinks, NewPlace, NewDish, PhoneCall, Email, RussianFlag, UzbekFlag, UsaFlag, BigMeal, Leaf, LeafMid, LeafBL, LeafRight, Meal1, Ins, BigPizza }